### ISSUE TITLE
Grunt task description

### ISSUE THREAD

**Issue by Rudloff** [timkelty/shipit-utils#4]
If I register a task like this:

``` js
utils.registerTask(gruntOrShipit, 'foobar', function () {
    //...
});
```

It will look like this in `grunt --help`:

```
Available tasks
shipit  Shipit Task
foobar  Custom task.
```

It would be nice to be able to set the task description.

**Comment by travco** [comment]
@Rudloff  Sniped with PR up, it was pretty easy to implement. We'll see if timkelty approves.

Also you chose a good time to lodge a feature request... it would be awesome if everything on github got turned around in six hours O.o

**Comment by timkelty** [comment]
Merged. Finally!
